#!/usr/bin/env python3
# Regenerates the committed SDL_GPU shader bytecode header from the GLSL sources.
#
# Pipeline: glslang (GLSL -> SPIR-V) then SDL_shadercross (SPIR-V -> MSL/DXIL, applying
# the SDL_GPU resource-binding remap per target). SPIRV covers Vulkan (Linux, Windows,
# macOS-via-MoltenVK); MSL covers Metal (macOS/iOS); DXIL covers D3D12 (Windows). DXIL
# needs a DXC-enabled shadercross, which has no macOS prebuilt — so on macOS the DXIL
# array is emitted empty and a Linux CI job (13 MB DXC prebuilt) regenerates the header
# with it filled in. The array is ALWAYS declared so the backend compiles either way.
# The generated header is checked in; an ordinary build needs neither tool. This script
# is developer/CI-only (run via the CMake `sdlgpu-shaders` target or by hand).
#
# Usage: gen_shaders.py <src_dir> <out_header> [glslang] [shadercross]

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# (source filename, glslang stage, shadercross stage)
SHADERS = [
    ("scene.vert", "vert", "vertex"),
    ("scene.frag", "frag", "fragment"),
]


def transpile(shadercross, spv, dest, sc_stage, out):
    # Returns the transpiled bytes, or b"" if the tool cannot produce this target (e.g.
    # DXIL without a DXC-enabled shadercross emits an empty file rather than failing).
    try:
        subprocess.run(
            [shadercross, str(spv), "-s", "SPIRV", "-d", dest, "-t", sc_stage, "-o", str(out)],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return b""
    return out.read_bytes() if out.exists() else b""


def compile_one(src_dir, name, gl_stage, sc_stage, glslang, shadercross, tmp):
    spv = tmp / f"{name}.spv"
    subprocess.run(
        [glslang, "-V", "-S", gl_stage, str(src_dir / name), "-o", str(spv)],
        check=True,
        stdout=subprocess.DEVNULL,
    )
    spirv = spv.read_bytes()
    msl = transpile(shadercross, spv, "MSL", sc_stage, tmp / f"{name}.msl")
    dxil = transpile(shadercross, spv, "DXIL", sc_stage, tmp / f"{name}.dxil")
    return {"spirv": spirv, "msl": msl, "dxil": dxil}


def emit_array(out, symbol, data):
    out.append(f"static const unsigned char {symbol}[] = {{")
    if data:
        for i in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
            out.append(f"\t{row},")
    else:
        # MSVC rejects zero-length arrays; a single placeholder byte keeps it valid while
        # the length below stays 0, so the backend never reads it.
        out.append("\t0,")
    out.append("};")
    out.append(f"static const unsigned int {symbol}_len = {len(data)};")
    out.append("")


def main():
    src_dir = Path(sys.argv[1])
    out_header = Path(sys.argv[2])
    glslang = sys.argv[3] if len(sys.argv) > 3 else "glslangValidator"
    shadercross = sys.argv[4] if len(sys.argv) > 4 else "shadercross"

    out = [
        "#pragma once",
        "",
        "// Auto-generated by gen_shaders.py. Do not edit; regenerate via the",
        "// `sdlgpu-shaders` CMake target. MSL entrypoint is \"main0\", SPIR-V/DXIL is \"main\".",
        "// A zero-length array means that format was not produced by the build host.",
        "",
    ]

    populated = {"spirv": 0, "msl": 0, "dxil": 0}
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        for name, gl_stage, sc_stage in SHADERS:
            blobs = compile_one(src_dir, name, gl_stage, sc_stage, glslang, shadercross, tmp)
            base = "g_" + name.replace(".", "_")
            for fmt in ("spirv", "msl", "dxil"):
                emit_array(out, f"{base}_{fmt}", blobs[fmt])
                if blobs[fmt]:
                    populated[fmt] += 1

    out_header.write_text("\n".join(out))

    # Keep the committed header clang-format-clean (CI formats every header under miniwin).
    clang_format = shutil.which("clang-format")
    if clang_format:
        subprocess.run([clang_format, "-i", "--style=file", str(out_header)], check=False)

    have = ", ".join(f for f, n in populated.items() if n)
    print(f"wrote {out_header} ({len(SHADERS)} shaders; formats present: {have or 'none'})")


if __name__ == "__main__":
    main()
